# Generated by Django 2.1.3 on 2018-11-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField()),
                ('response_id', models.PositiveIntegerField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Questionnaire')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='message',
            name='response_id',
        ),
        migrations.AlterUniqueTogether(
            name='questionnairestructure',
            unique_together={('questionnaire', 'question_id', 'response_id')},
        ),
    ]
